# Generated by Django 4.2 on 2023-05-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercars',
            old_name='car',
            new_name='cars',
        ),
    ]
