# Generated by Django 4.2 on 2023-05-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_car_usercars_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercars',
            old_name='cars',
            new_name='car',
        ),
    ]
